# Generated by Django 2.2.5 on 2019-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEDOCAL', '0003_auto_20190924_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='haplo',
            field=models.CharField(choices=[('1/1', '1/1'), ('1/2', '1/2'), ('1/3', '1/3'), ('2/2', '2/2'), ('2/3', '2/3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='v6',
            field=models.CharField(choices=[('GG', 'GG'), ('GA', 'GA'), ('AA', 'AA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='v7',
            field=models.CharField(choices=[('CC', 'CC'), ('CT', 'CT'), ('TT', 'TT')], max_length=2),
        ),
    ]
