# Generated by Django 2.2.5 on 2019-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEDOCAL', '0005_dose_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='commenter',
            field=models.CharField(choices=[('Moi', 'Moi'), ('Mon Medecin', 'Mon Medecin'), ('Un Proche', 'Un Proche')], default='nothing', max_length=20),
            preserve_default=False,
        ),
    ]
