# Generated by Django 2.2.5 on 2019-09-24 05:59

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20)),
                ('adding_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthdate', models.DateField(default=datetime.date(1950, 1, 1))),
                ('v6', models.CharField(choices=[(1, 'GG'), (2, 'GA'), (3, 'AA')], max_length=2)),
                ('v7', models.CharField(choices=[(1, 'CC'), (2, 'CT'), (3, 'TT')], max_length=2)),
                ('haplo', models.CharField(choices=[(1, '1/1'), (2, '1/2'), (2, '1/3'), (3, '2/2'), (3, '2/3')], max_length=2)),
            ],
        ),
    ]
