# Generated by Django 2.2.5 on 2019-09-24 06:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WEDOCAL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dose_date', models.DateField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEDOCAL.Patient')),
            ],
        ),
    ]
