# Generated by Django 2.2.5 on 2019-09-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEDOCAL', '0002_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
