# Generated by Django 2.2.5 on 2019-09-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEDOCAL', '0004_auto_20190924_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='comment',
            field=models.TextField(default='nothing', max_length=1000),
        ),
    ]
